from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re
import shutil
from typing import TYPE_CHECKING

from bakenn.artifacts import load_manifest
from bakenn.errors import CompileError

from ._export import staged_export

if TYPE_CHECKING:
    from bakenn.backend.portable_c import CompilationArtifacts


# Arduino Library Specification: letters, digits, spaces, "_", "." and "-";
# starts with a letter or digit; 3 to 63 characters.
_LIBRARY_NAME = re.compile(r"[A-Za-z0-9][A-Za-z0-9 _.\-]{2,62}")
_LIBRARY_VERSION = re.compile(r"(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)")
_BOARD_INDEPENDENT_KERNELS = ("portable.", "optimized.")
_EXAMPLE = "Infer"


@dataclass(frozen=True)
class ArduinoLibrary:
    root: Path
    source: Path
    example: Path
    name: str
    model_symbol: str


def _require_board_independent(
    artifacts: "CompilationArtifacts",
) -> dict[str, object]:
    """Reject artifacts an Arduino core cannot build without extra flags.

    An Arduino library cannot add include paths or compile definitions, so
    bundled vendor kernels and target-specific placement stay out of scope.
    """

    manifest = load_manifest(artifacts.manifest)
    backend = manifest["backend"]
    assert isinstance(backend, dict)
    if artifacts.support_sources or manifest.get("bundled_dependencies"):
        raise CompileError(
            "Arduino library export requires artifacts without bundled CMSIS-NN or "
            "ESP-NN sources; recompile without enable_cmsis_nn/enable_esp_nn"
        )
    if "requantization_placement" in backend:
        raise CompileError(
            "Arduino library export does not support requantization_in_dram; "
            "recompile without it"
        )
    target_specific = sorted(
        {
            str(selection["implementation"])
            for selection in backend["selections"]
            if not str(selection["implementation"]).startswith(_BOARD_INDEPENDENT_KERNELS)
        }
    )
    if target_specific:
        raise CompileError(
            "Arduino library export requires portable or generic optimized kernels, "
            f"got {', '.join(target_specific)}; recompile for target 'portable32'"
        )
    return manifest


def _sketch_source(symbol: str) -> str:
    macro = symbol.upper()
    return f"""// Generated by BakeNN. Runs {symbol} once per loop and prints its timing and
// INT8 output codes. Replace the zero-point input with real quantized data.
#include <{symbol}.h>

#if {macro}_ARENA_SIZE > 0u
alignas({macro}_ARENA_ALIGNMENT) static uint8_t model_arena[{macro}_ARENA_SIZE];
#else
static uint8_t *const model_arena = nullptr;
#endif
static int8_t model_input[{macro}_INPUT_SIZE];
static int8_t model_output[{macro}_OUTPUT_SIZE];

void setup() {{
  Serial.begin(115200);
  for (size_t index = 0; index < {macro}_INPUT_SIZE; ++index) {{
    model_input[index] = (int8_t){macro}_INPUT_ZERO_POINT;
  }}
}}

void loop() {{
  const unsigned long start = micros();
  {symbol}_infer(model_arena, model_input, model_output);
  const unsigned long elapsed = micros() - start;
  Serial.print("BAKENN inference_us=");
  Serial.print(elapsed);
  Serial.print(" output=");
  for (size_t index = 0; index < {macro}_OUTPUT_SIZE; ++index) {{
    Serial.print(' ');
    Serial.print((int)model_output[index]);
  }}
  Serial.println();
  delay(1000);
}}
"""


def _library_properties(name: str, version: str, symbol: str) -> str:
    return (
        f"name={name}\n"
        f"version={version}\n"
        "author=Generated by BakeNN\n"
        "maintainer=Generated by BakeNN <https://github.com/scienthoon/bakeNN>\n"
        f"sentence=INT8 model {symbol} compiled to standalone C by BakeNN.\n"
        f"paragraph=Call {symbol}_infer(arena, input, output). Buffer sizes and "
        f"quantization parameters are macros in {symbol}.h; see the {_EXAMPLE} example.\n"
        "category=Data Processing\n"
        "url=https://github.com/scienthoon/bakeNN\n"
        "architectures=*\n"
        f"includes={symbol}.h\n"
    )


def export_arduino_library(
    artifacts: "CompilationArtifacts",
    output_dir: str | Path,
    *,
    name: str | None = None,
    version: str = "1.0.0",
) -> ArduinoLibrary:
    """Package a board-independent model as an Arduino library.

    The library is published atomically into an absent or empty directory and
    builds with any 32-bit Arduino core. Place it in the sketchbook
    ``libraries`` folder and open the bundled example.
    """

    manifest = _require_board_independent(artifacts)
    symbol = str(manifest["model"])
    library_name = symbol if name is None else name
    if not isinstance(library_name, str) or not _LIBRARY_NAME.fullmatch(library_name):
        raise CompileError(
            f"invalid Arduino library name {library_name!r}: use 3 to 63 letters, "
            "digits, spaces, '_', '.' or '-', starting with a letter or digit"
        )
    if not isinstance(version, str) or not _LIBRARY_VERSION.fullmatch(version):
        raise CompileError(
            f"invalid Arduino library version {version!r}: expected MAJOR.MINOR.PATCH"
        )
    output = Path(output_dir)
    with staged_export(artifacts.output_dir, output) as staging:
        # Arduino compiles every C file under src/ and ignores the manifest
        # and reports, so the artifact set stays complete and verifiable.
        shutil.copytree(artifacts.output_dir, staging / "src")
        load_manifest(staging / "src" / artifacts.manifest.name)
        example = staging / "examples" / _EXAMPLE
        example.mkdir(parents=True)
        (example / f"{_EXAMPLE}.ino").write_text(_sketch_source(symbol), encoding="utf-8")
        (staging / "library.properties").write_text(
            _library_properties(library_name, version, symbol), encoding="utf-8"
        )
    return ArduinoLibrary(
        root=output,
        source=output / "src",
        example=output / "examples" / _EXAMPLE / f"{_EXAMPLE}.ino",
        name=library_name,
        model_symbol=symbol,
    )


__all__ = ["ArduinoLibrary", "export_arduino_library"]
